### ISSUE TITLE
【課題】221106

### ISSUE THREAD

**Issue by technicakidz** [shelmi34/my-first-blog#14]
### TODO

- [x] PR(PullRequests) を作成する
  - README の追加(修正)をしたもの
  - できたらリンク(PR)付きでメッセージする
  - レビューをもらう
  - マージする
- [ ] `post_list` の表示問題解決
  - 必要なもの(pip, python, django など)を都度エラーメッセージの度にインストールする
  - web サーバ、仮想環境を起動する.. といった手順を踏んで表示を確認する
  - 管理画面に入る
  - 「Django テンプレート」の章を改めて実装/確認する

**Comment by technicakidz** [comment]
`git rm` コマンドについての回答を記載しました。
https://github.com/shelmi34/my-first-blog/issues/12#issuecomment-1288051614

**Comment by shelmi34** [comment]
管理画面に入ると、このような画面になりました。チュートリアルのような画面は出てきていませんが、これで合っているのですか？

![Image](https://user-images.githubusercontent.com/115387649/200476289-7d8cc4ac-cbde-4405-aaaf-3a27dad361f6.png)

**Comment by technicakidz** [comment]
@shelmi34 
はい、こちらの画面で投稿やユーザデータが確認できると思います。
これらは、 `post_list` テンプレートなどで表示されるデータになるので、表示反映の確認時に参照するものになります。

**Comment by technicakidz** [comment]
@shelmi34 
`post_list` の表示されない原因がわかったので共有します．
下記にチュートリアルで追加する１行がぬけていそうでした．該当箇所は学習のためにチュートリアルドキュメントをご自身で探してみしょう！
https://github.com/shelmi34/my-first-blog/blob/dfa7650ce399fda994a3d56c45cffad4cbb9e9df/mysite/urls.py#L19-L21
![スクリーンショット 0004-11-09 10 24 28](https://user-images.githubusercontent.com/6193750/200713889-2f596eb7-bae7-41db-b002-066ee44700ba.png)
